# PyTorch로 시작하는 딥러닝 입문
https://wikidocs.net/book/2788
## 01. 선형회귀
파이토치로 선형회귀 구현하기
### 1. 기본 셋팅

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 같은 결과가 나오도록 랜덤시드 설정
torch.manual_seed(1)

### 2. 변수 선언

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [5]:
print('x_train', x_train)
print('x_train shape', x_train.shape)
print()
print('y_train', y_train)
print('y_train shape', y_train.shape)

x_train tensor([[1.],
        [2.],
        [3.]])
x_train shape torch.Size([3, 1])

y_train tensor([[2.],
        [4.],
        [6.]])
y_train shape torch.Size([3, 1])


### 3. 가중치와 편향 초기화
션형회귀란 학습데이터와 가장 잘 맞는 하나의 직선을 찾는 일  
가장 잘 맞는 직선을 정의하는 것은 W(가중치)와 b(편향)  

In [6]:
# 가중치 W를 0으로 초기화, 학습을 통해 값이 변경되는 변수임(requires_grad=True)을 명시
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [7]:
# 편향 b를 0으로 초기화, 학습을 통해 값이 변경되는 변수임(requires_grad=True)을 명시
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


### 4. 가설 세우기
가설 H = Wx + b

In [8]:
H = W*x_train + b
print(H)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


### 5. 비용함수 선언하기
비용함수 cost = MSE = 평균(실제값 - 예측값)**2

In [9]:
cost = torch.mean((H - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


### 6. 경사하강법 구현하기
SGD는 경사하강법의 일종  
학습대상인 W, b 가 SGD의 입력값이 됨

In [10]:
optimizer = optim.SGD([W, b], lr=0.01)

In [11]:
# optimizer.zero_grad() 를 통해 gradient를 0으로 초기화
# 기울기를 초기화해야만 새로운 가중치 편향에 대해서 새로운 기울기를 구할 수 있음
# zero_grad()를 안하면 이건 값에 새로운 값이 누적됨
optimizer.zero_grad()

In [12]:
# 비용함수 cost를 미분하여 gradient 계산
cost.backward()

In [13]:
# step()를 통해 [W, b - (리턴되는 변수들의 기울기 * 학습률)] 값을 업데이트
optimizer.step()

### 7. 여러번 학습시키기

In [16]:
n_epochs = 999

for epoch in range(n_epochs+1):
    
    # H 계산
    H = W * x_train + b
    
    # cost 계산
    cost = torch.mean((H - y_train) ** 2)
    
    # cost로 H(x) 업데이트
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 값 print
    if epoch % 100 == 0:
        print(f'Epoch: {epoch}/{n_epochs} \t가중치 W: {W.item():.3f} \t편향 b: {b.item():.3f} \t비용 cost: {cost.item():.3f}')

Epoch: 0/999 	가중치 W: 0.353 	편향 b: 0.151 	비용 cost: 14.771
Epoch: 100/999 	가중치 W: 1.746 	편향 b: 0.577 	비용 cost: 0.048
Epoch: 200/999 	가중치 W: 1.801 	편향 b: 0.453 	비용 cost: 0.030
Epoch: 300/999 	가중치 W: 1.843 	편향 b: 0.356 	비용 cost: 0.018
Epoch: 400/999 	가중치 W: 1.877 	편향 b: 0.280 	비용 cost: 0.011
Epoch: 500/999 	가중치 W: 1.903 	편향 b: 0.220 	비용 cost: 0.007
Epoch: 600/999 	가중치 W: 1.924 	편향 b: 0.173 	비용 cost: 0.004
Epoch: 700/999 	가중치 W: 1.940 	편향 b: 0.136 	비용 cost: 0.003
Epoch: 800/999 	가중치 W: 1.953 	편향 b: 0.107 	비용 cost: 0.002
Epoch: 900/999 	가중치 W: 1.963 	편향 b: 0.084 	비용 cost: 0.001


## 02. 자동 미분
w = 2  
z = 2w^2 + b  
z' = 4w  

In [17]:
w = torch.tensor(2.0, requires_grad=True)

In [18]:
y = w**2
z = 2*y + 5

In [19]:
# w에 대해서 미분
z.backward()

In [20]:
print(f'수식을 w로 미분한 값: {w.grad}')

수식을 w로 미분한 값: 8.0


## 03. 다중 선형 회귀
독립변수가 1개인 경우 H = Wx +b  
독립변수가 3개인 경우 H = w1x1 + w2x2 + w3x3 + b

In [51]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [52]:
# 가중치 3개, 편향 1개 선언
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [53]:
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=0.00001)

n_epochs = 100

for epoch in range(n_epochs+1):
    
    # H 계산
    H = w1*x1_train + w2*x2_train + w3*x3_train + b
    
    # cost 계산
    cost = torch.mean((H - y_train) ** 2)
    
    # cost로 H(x) 업데이트
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 값 print
    if epoch % 10 == 0:
        print(f'Epoch: {epoch}/{n_epochs}')
        print(f'가중치 w1: {w1.item():.3f} \t가중치 w2: {w2.item():.3f} \t가중치 w3: {w3.item():.3f}')
        print(f'편향 b: {b.item():.3f} \t비용 cost: {cost.item():.3f}')
        print()

Epoch: 0/100
가중치 w1: 0.294 	가중치 w2: 0.294 	가중치 w3: 0.297
편향 b: 0.003 	비용 cost: 29661.801

Epoch: 10/100
가중치 w1: 0.667 	가중치 w2: 0.665 	가중치 w3: 0.675
편향 b: 0.008 	비용 cost: 1.898

Epoch: 20/100
가중치 w1: 0.669 	가중치 w2: 0.666 	가중치 w3: 0.676
편향 b: 0.008 	비용 cost: 1.619

Epoch: 30/100
가중치 w1: 0.670 	가중치 w2: 0.665 	가중치 w3: 0.676
편향 b: 0.008 	비용 cost: 1.612

Epoch: 40/100
가중치 w1: 0.670 	가중치 w2: 0.665 	가중치 w3: 0.676
편향 b: 0.008 	비용 cost: 1.605

Epoch: 50/100
가중치 w1: 0.671 	가중치 w2: 0.664 	가중치 w3: 0.676
편향 b: 0.008 	비용 cost: 1.598

Epoch: 60/100
가중치 w1: 0.671 	가중치 w2: 0.663 	가중치 w3: 0.676
편향 b: 0.008 	비용 cost: 1.591

Epoch: 70/100
가중치 w1: 0.672 	가중치 w2: 0.663 	가중치 w3: 0.676
편향 b: 0.008 	비용 cost: 1.584

Epoch: 80/100
가중치 w1: 0.672 	가중치 w2: 0.662 	가중치 w3: 0.676
편향 b: 0.008 	비용 cost: 1.577

Epoch: 90/100
가중치 w1: 0.673 	가중치 w2: 0.662 	가중치 w3: 0.676
편향 b: 0.008 	비용 cost: 1.570

Epoch: 100/100
가중치 w1: 0.674 	가중치 w2: 0.661 	가중치 w3: 0.676
편향 b: 0.008 	비용 cost: 1.564



3개의 독립변수를 행렬로 표현하기

In [54]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

print('x_train shape: ', x_train.shape)
print('y_train shape: ', y_train.shape)

x_train shape:  torch.Size([5, 3])
y_train shape:  torch.Size([5, 1])


In [55]:
# 가중치 W 선언
# x_train(5, 3) * w(?, ?) = y_train(5, 1) w의 shape을 계산할 수 있어야함
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [56]:
# matmul() 행렬의 곱셈을 의미
H = x_train.matmul(W) + b

In [57]:
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    H = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((H - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, H.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670898
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.482086
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

## 04. nn.Module로 구현하는 선형 회귀
### 1. 단순 선형 회귀

In [58]:
# import torch.nn as nn
# import torch.nn.functional as F

In [78]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [79]:
# 단순선형회기 이므로 input_dim=1, output_dim=1
model = nn.Linear(1, 1)

In [80]:
# 모델에는 가중치와 편향이 저장되어 있음
print(list(model.parameters()))

[Parameter containing:
tensor([[0.1390]], requires_grad=True), Parameter containing:
tensor([-0.1224], requires_grad=True)]


In [81]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [82]:
nb_epochs = 1000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/1000 Cost: 17.088327
Epoch  100/1000 Cost: 0.030164
Epoch  200/1000 Cost: 0.018639
Epoch  300/1000 Cost: 0.011518
Epoch  400/1000 Cost: 0.007117
Epoch  500/1000 Cost: 0.004398
Epoch  600/1000 Cost: 0.002718
Epoch  700/1000 Cost: 0.001679
Epoch  800/1000 Cost: 0.001038
Epoch  900/1000 Cost: 0.000641
Epoch 1000/1000 Cost: 0.000396


In [83]:
# w, b 최적화 확인
# x에 임의의 값 4를 넣어 모델이 예측하는 y값 확인

In [84]:
# 임의의 값 4 생성
new_var = torch.FloatTensor([[4.0]])

# 입력값 4에 대한 예측값
pred_y = model(new_var)
print('입력값 4에 대한 예측값: ', pred_y)

입력값 4에 대한 예측값:  tensor([[7.9602]], grad_fn=<AddmmBackward>)


x_train, y_train의 관계를 보면 이 모델은 y=2x의 형태를 가지고 있다.  
따라서 입력값 4에 대해서는 8을 예측해야 잘 예측했다고 본다.

In [85]:
# 학습 후 W, b 값 확인
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9769]], requires_grad=True), Parameter containing:
tensor([0.0524], requires_grad=True)]


학습 전 W: 0.1390, b: -0.1224  
학습 후 W: 1.9769, b: 0.0524
### 2. 다중 선형 회귀 구현하기

In [86]:
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# torch.manual_seed(1)

In [91]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

print('x_train shape: ', x_train.shape)
print('y_train shape: ', y_train.shape)

x_train shape:  torch.Size([5, 3])
y_train shape:  torch.Size([5, 1])


In [92]:
# 다중 선형 회귀므로 input_dim=3, output_dim=1
model = nn.Linear(3, 1)

In [93]:
# 학습 전 W, b 값 확인
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.0421, -0.0520,  0.0837]], requires_grad=True), Parameter containing:
tensor([-0.0023], requires_grad=True)]


In [94]:
# optim 설정
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [95]:
nb_epochs = 1000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/1000 Cost: 29999.046875
Epoch  100/1000 Cost: 7.455994
Epoch  200/1000 Cost: 7.120210
Epoch  300/1000 Cost: 6.801655
Epoch  400/1000 Cost: 6.499341
Epoch  500/1000 Cost: 6.212316
Epoch  600/1000 Cost: 5.939743
Epoch  700/1000 Cost: 5.680788
Epoch  800/1000 Cost: 5.434702
Epoch  900/1000 Cost: 5.200678
Epoch 1000/1000 Cost: 4.978209


In [96]:
# w, b 최적화 확인
# x에 임의의 값 73, 80, 75를 넣어 모델이 예측하는 y값 확인

In [97]:
# 임의의 값 73, 80, 75 생성
new_var = torch.FloatTensor([[73, 80, 75]])

# 예측
pred_y = model(new_var)
print('입력값 [[73, 80, 75]]에 대한 예측값: ', pred_y)

입력값 [[73, 80, 75]]에 대한 예측값:  tensor([[153.8672]], grad_fn=<AddmmBackward>)


In [98]:
# 학습 후 W, b 값 확인
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7328, 0.6701, 0.6235]], requires_grad=True), Parameter containing:
tensor([0.0066], requires_grad=True)]


## 05. 클래스로 파이토치 모델 구현하기
### 1. 단순 선형 회귀 클래스로 구현하기

In [99]:
class LRModel(nn.Module):  # torch.nn.Module을 상속받는 클래스
    def __init__(self):
        super().__init__()  # 모델의 구조와 동작을 정의하는 생성자 정의 = 속성값 초기화
        self.linear = nn.Linear(1, 1) # 단순선형회귀이므로 Input_dim=1, output_dim=1
        
    def forward(self, x):
        return self.linear(x)

In [100]:
# 모델 선언
model = LRModel()

In [101]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [102]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [103]:
nb_epochs = 1000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/1000 Cost: 4.610449
Epoch  100/1000 Cost: 0.040473
Epoch  200/1000 Cost: 0.025010
Epoch  300/1000 Cost: 0.015454
Epoch  400/1000 Cost: 0.009550
Epoch  500/1000 Cost: 0.005901
Epoch  600/1000 Cost: 0.003647
Epoch  700/1000 Cost: 0.002253
Epoch  800/1000 Cost: 0.001392
Epoch  900/1000 Cost: 0.000860
Epoch 1000/1000 Cost: 0.000532


### 2. 다중 선형 회귀 클래스로 구현하기

In [126]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

print('x_train shape: ', x_train.shape)
print('y_train shape: ', y_train.shape)

x_train shape:  torch.Size([5, 3])
y_train shape:  torch.Size([5, 1])


In [127]:
class Multi_LR_Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [128]:
model = Multi_LR_Model()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [129]:
nb_epochs = 1000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/1000 Cost: 25607.140625
Epoch  100/1000 Cost: 0.715505
Epoch  200/1000 Cost: 0.687857
Epoch  300/1000 Cost: 0.661689
Epoch  400/1000 Cost: 0.636900
Epoch  500/1000 Cost: 0.613430
Epoch  600/1000 Cost: 0.591174
Epoch  700/1000 Cost: 0.570103
Epoch  800/1000 Cost: 0.550096
Epoch  900/1000 Cost: 0.531124
Epoch 1000/1000 Cost: 0.513116


## 06. 미니 배치와 데이터 로드
전체 데이터가 2000일 때 미니배치 사이즈를 200으로 한다면 이터레이션(iteration)의 수는 10개 = 1epoch 당 매개변수 업데이트가 10번 이루어짐

In [2]:
# import torch
# import torch.nn as nn
# import torch.nn.functional as F

In [3]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [4]:
# 데이터 생성
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [5]:
# 생성된 데이터를 dataset로 저장
dataset = TensorDataset(x_train, y_train)

**데이터로더(DataLoader)**  
x, y값을 연결하여 자동으로 미니배치, 셔플을 나눠줌

In [6]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [8]:
print('x_train shape: ', x_train.shape)
print('y_train shape: ', y_train.shape)

x_train shape:  torch.Size([5, 3])
y_train shape:  torch.Size([5, 1])


In [11]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [12]:
n_epochs = 20

for epoch in range(n_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        
        # H(x)계산
        prediction = model(x_train)
        
        # cost
        cost = F.mse_loss(prediction, y_train)
        
        # update
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print(f'Epoch: {epoch}/{n_epochs}\tBatch: {batch_idx+1}/{len(dataloader)}\tCost: {cost.item():.4f}')

Epoch: 0/20	Batch: 1/3	Cost: 95730.7812
Epoch: 0/20	Batch: 2/3	Cost: 34905.6328
Epoch: 0/20	Batch: 3/3	Cost: 6173.3325
Epoch: 1/20	Batch: 1/3	Cost: 3868.2461
Epoch: 1/20	Batch: 2/3	Cost: 868.5018
Epoch: 1/20	Batch: 3/3	Cost: 225.3134
Epoch: 2/20	Batch: 1/3	Cost: 97.3834
Epoch: 2/20	Batch: 2/3	Cost: 49.6230
Epoch: 2/20	Batch: 3/3	Cost: 28.8818
Epoch: 3/20	Batch: 1/3	Cost: 0.2628
Epoch: 3/20	Batch: 2/3	Cost: 3.5507
Epoch: 3/20	Batch: 3/3	Cost: 3.4606
Epoch: 4/20	Batch: 1/3	Cost: 1.6231
Epoch: 4/20	Batch: 2/3	Cost: 2.0464
Epoch: 4/20	Batch: 3/3	Cost: 1.6532
Epoch: 5/20	Batch: 1/3	Cost: 2.0012
Epoch: 5/20	Batch: 2/3	Cost: 1.2254
Epoch: 5/20	Batch: 3/3	Cost: 2.8544
Epoch: 6/20	Batch: 1/3	Cost: 1.4274
Epoch: 6/20	Batch: 2/3	Cost: 2.0123
Epoch: 6/20	Batch: 3/3	Cost: 0.8556
Epoch: 7/20	Batch: 1/3	Cost: 1.9369
Epoch: 7/20	Batch: 2/3	Cost: 1.2409
Epoch: 7/20	Batch: 3/3	Cost: 0.5272
Epoch: 8/20	Batch: 1/3	Cost: 0.3816
Epoch: 8/20	Batch: 2/3	Cost: 2.3276
Epoch: 8/20	Batch: 3/3	Cost: 2.1239
Epoch: 

In [13]:
# 확인
new_var = torch.FloatTensor([[73, 80, 75]])
y_pred = model(new_var)
print('result: ', y_pred)  # 정답은 152

result:  tensor([[152.2337]], grad_fn=<AddmmBackward>)


## 07. 커스텀 데이터셋
### 1. 커스텀 데이터셋으로 선형회귀 구현하기

In [14]:
# import torch
# import torch.nn.functional as F
# from torch.utils.data import Dataset
# from torch.utils.data import DataLoader

In [15]:
class CustomDataset(torch.utils.data.Dataset):
    
    # 데이터셋 전처리
    def __init__(self):  
        self.x_data = [[73, 80, 75], 
                       [93, 88, 93], 
                       [89, 91, 90], 
                       [96, 98, 100], 
                       [73, 66, 70]]
        self.y_data = [[152],  [185], [180], [196], [142]]
        
    # 데이터셋 길이(=총 샘플수)
    def __len__(self):  
        return len(self.x_data)
        
    # 데이터셋에서 특정 1개의 샘플을 가져오는 함수
    # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치 Tensor 형태로 리턴
    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

In [16]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [17]:
model = torch.nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [18]:
n_epochs = 20

for epoch in range(n_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        
        # H(x)계산
        prediction = model(x_train)
        
        # cost
        cost = F.mse_loss(prediction, y_train)
        
        # update
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print(f'Epoch: {epoch}/{n_epochs}\tBatch: {batch_idx+1}/{len(dataloader)}\tCost: {cost.item():.4f}')

Epoch: 0/20	Batch: 1/3	Cost: 10159.8496
Epoch: 0/20	Batch: 2/3	Cost: 4486.1582
Epoch: 0/20	Batch: 3/3	Cost: 1443.0574
Epoch: 1/20	Batch: 1/3	Cost: 295.5027
Epoch: 1/20	Batch: 2/3	Cost: 110.8369
Epoch: 1/20	Batch: 3/3	Cost: 28.6061
Epoch: 2/20	Batch: 1/3	Cost: 9.5145
Epoch: 2/20	Batch: 2/3	Cost: 4.2460
Epoch: 2/20	Batch: 3/3	Cost: 0.1377
Epoch: 3/20	Batch: 1/3	Cost: 0.4370
Epoch: 3/20	Batch: 2/3	Cost: 1.2320
Epoch: 3/20	Batch: 3/3	Cost: 0.1835
Epoch: 4/20	Batch: 1/3	Cost: 0.4839
Epoch: 4/20	Batch: 2/3	Cost: 0.5528
Epoch: 4/20	Batch: 3/3	Cost: 1.1422
Epoch: 5/20	Batch: 1/3	Cost: 0.6672
Epoch: 5/20	Batch: 2/3	Cost: 0.5440
Epoch: 5/20	Batch: 3/3	Cost: 0.6153
Epoch: 6/20	Batch: 1/3	Cost: 0.7734
Epoch: 6/20	Batch: 2/3	Cost: 0.5498
Epoch: 6/20	Batch: 3/3	Cost: 0.5452
Epoch: 7/20	Batch: 1/3	Cost: 0.1301
Epoch: 7/20	Batch: 2/3	Cost: 0.5693
Epoch: 7/20	Batch: 3/3	Cost: 0.8627
Epoch: 8/20	Batch: 1/3	Cost: 0.3523
Epoch: 8/20	Batch: 2/3	Cost: 0.2299
Epoch: 8/20	Batch: 3/3	Cost: 1.4807
Epoch: 9/20	B

In [19]:
# 확인
new_var = torch.FloatTensor([[73, 80, 75]])
y_pred = model(new_var)
print('result: ', y_pred)  # 정답은 152

result:  tensor([[150.9812]], grad_fn=<AddmmBackward>)
