# 4. 선형계층

## 실습4.4 - 1. 행렬곱 구현하기

In [1]:
import torch

In [2]:
x = torch.FloatTensor(4, 3)
W = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
b = torch.FloatTensor([2, 2])

In [3]:
def linear(x, W, b):
    y = torch.matmul(x, W) + b
    return y

In [4]:
y = linear(x, W, b)
y.size()

torch.Size([4, 2])

## 실습4.4 - 2. torch.nn.Module

In [5]:
import torch.nn as nn

In [6]:
class MyLinear(nn.Module):
    
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
        
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        return y

In [11]:
linear = MyLinear(3, 2)
y = linear(x)
y

tensor([[9.4980e-36, 5.4183e-39],
        [9.4980e-36, 5.4219e-39],
        [9.4980e-36, 5.4216e-39],
        [9.4980e-36, 5.4219e-39]])

## 실습4.4 - 3. nn.Parameter

In [23]:
class MyLinear(nn.Module):
    
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
        
    def forward(self, x):
        # x.shape = [batch_size 4, input 3]
        # W.shape = [input 3, output 2]
        # b.shape = [output 2]
        y = torch.matmul(x, self.W) + self.b
        # y.shape = [batch_size 4, output 2]
        return y

In [14]:
linear = MyLinear(3, 2)
y = linear(x)
y

tensor([[0.0000, 0.0006],
        [0.0000, 0.0006],
        [0.0000, 0.0006],
        [0.0000, 0.0006]], grad_fn=<AddBackward0>)

In [15]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[0.0000e+00, 4.6566e-10],
        [0.0000e+00, 4.6566e-10],
        [1.4013e-44, 4.6566e-10]], requires_grad=True)
Parameter containing:
tensor([-0.0000, 0.0006], requires_grad=True)


## 실습4.4 - 4. nn.Linear

In [16]:
linear = nn.Linear(3, 2)
y = linear(x)

for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[-0.4110,  0.2365, -0.1491],
        [ 0.2478, -0.4533, -0.1433]], requires_grad=True)
Parameter containing:
tensor([0.0900, 0.5121], requires_grad=True)


In [17]:
x.shape

torch.Size([4, 3])

In [18]:
y.shape

torch.Size([4, 2])

In [19]:
class MyLinear(nn.Module):
    
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        y = self.linear(x)
        return y

In [20]:
linear = MyLinear(3, 2)
y = linear(x)

for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.5691,  0.4155,  0.3506],
        [-0.0204,  0.4870, -0.2747]], requires_grad=True)
Parameter containing:
tensor([ 0.5713, -0.0048], requires_grad=True)


In [22]:
x.device

device(type='cpu')