# pytorch 설치

In [3]:
import torch
print(torch.__version__)

1.13.1


# 3장 파이토치 튜토리얼

## 3. 파이토치 텐서 생성하기

In [5]:
# float tensor
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [6]:
# long tensor
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [7]:
# byte tensor
bt = torch.ByteTensor([[1, 2],
                       [3, 4]])
bt

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [8]:
# 임의의 텐서 만들기
x = torch.FloatTensor(3, 2)
x

tensor([[1., 2.],
        [3., 4.],
        [0., 2.]])

## 4. Numpy 호환

In [11]:
import numpy as np

# 넘파이 array 생성
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [12]:
# 넘파이를 파이토치 텐서로 변환
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [13]:
# 파이토치 텐서를 넘파이로 변환
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## 5. 텐서 타입 변환

In [14]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [15]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

## 6. 텐서 크기 구하기

In [16]:
x = torch.FloatTensor([[[1, 2], [3, 4]],
                       [[5, 6], [7, 8]],
                       [[9, 10], [11, 12]]])
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [17]:
# 텐서 차원 구하기
print(x.dim())
print(len(x.size()))

3
3


## 실습3.5 - 1. view함수
- 원하는 shape에 맞춰 텐서들 재배열
- view() 안에 텐서 갯수 유지해서 작성

In [20]:
x = torch.FloatTensor([[[1, 2], [3, 4]],
                       [[5, 6], [7, 8]],
                       [[9, 10], [11, 12]]])

# view() 안에 텐서의 갯수 유지해서 작성
print(x.view(12))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [21]:
print(x.view(3, 4))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [22]:
print(x.view(3, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [23]:
# -1로 자동 계산
print(x.view(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


## 실습3.5 - 2. squeeze함수
- 차원의 크기가 1인 차원 없앰
- ()안에 차원 지정 가능 ex. squeeze(0)

In [24]:
x = torch.FloatTensor([[[1, 2], [3, 4]]])
print(x.size())

torch.Size([1, 2, 2])


In [25]:
print(x.squeeze().size())

torch.Size([2, 2])


## 실습3.5 - 3. unsqueeze함수
- 차원의 크기가 1인 차원 삽입
- ()안에 차원 지정 가능 ex. unsqueeze(0)

In [26]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.size())
print(x.unsqueeze(1).size())
print(x.unsqueeze(-1).size())

torch.Size([2, 2])
torch.Size([2, 1, 2])
torch.Size([2, 2, 1])


## 실습3.6 - 1. 인덱싱과 슬라이싱

In [27]:
x = torch.FloatTensor([[[1, 2], [3, 4]],
                       [[5, 6], [7, 8]],
                       [[9, 10], [11, 12]]])
print(x.shape)

torch.Size([3, 2, 2])


In [28]:
# 첫번재 차원 인덱싱
print(x[0])

tensor([[1., 2.],
        [3., 4.]])


In [29]:
# 각 차원의 첫번째 값 가져오기
print(x[:, 0])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [31]:
# 각 텐서의 첫번째 값 가져오기
print(x[:, :, 0])

tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])


In [32]:
# 특정 부분 지정하여 가져오기
print(x[1:2, 1:, :])

tensor([[[7., 8.]]])


## 실습3.6 - 2. split함수
10개의 텐서를 4개씩 나눠라

In [34]:
x = torch.FloatTensor(10, 4)
splits = x.split(4, dim=0)
for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


## 실습3.6 - 3. chunk함수
10개의 텐서를 최대한 비슷하게 4등분해라

In [36]:
x = torch.FloatTensor(10, 4)
chunks = x.chunk(4, dim=0)
for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 4])


## 실습3.6 - 4. Index Select함수
텐서의 순서에 따라 골라오는 함수

In [41]:
x = torch.FloatTensor([[[1, 1],
                        [2, 2]],
                       [[3, 3],
                        [4, 4]],
                       [[5, 5],
                        [6, 6]]])

In [42]:
# 2번째 불러오고 다음에 1번째 불러오기
indice = torch.LongTensor([2, 1])

In [43]:
y = x.index_select(dim=0, index=indice)
print(y)

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])


## 실습3.6 - 5. concatenate함수
같은 차원의 데이터를 가로 또는 세로로 이어붙이기
## 실습3.6 - 6. stack함수
차원 쌓기

In [44]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
y = torch.FloatTensor([[11, 12, 13],
                       [14, 15, 16],
                       [17, 18, 19]])

In [46]:
z = torch.stack([x, y])
print(z.shape)
z

torch.Size([2, 3, 3])


tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[11., 12., 13.],
         [14., 15., 16.],
         [17., 18., 19.]]])

In [ ]:
z = torch.stack([x, y], dim=-1)
print(z.shape)
z

torch.Size([3, 3, 2])


tensor([[[ 1., 11.],
         [ 2., 12.],
         [ 3., 13.]],

        [[ 4., 14.],
         [ 5., 15.],
         [ 6., 16.]],

        [[ 7., 17.],
         [ 8., 18.],
         [ 9., 19.]]])

## 실습3.7 - 6. masked fill 함수
조건에 해당하는 값 변경

In [49]:
x = torch.FloatTensor([i for i in range(9)])
print(x)
x = x.reshape(3, -1)
print(x)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


In [50]:
mask = x > 4
print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [51]:
y = x.masked_fill(mask, value=-1)
y

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])