# 6. 경사하강법

## 실습6.5 경사하강법 구현

In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]
                           ])

In [4]:
x = torch.rand_like(target)
x.requires_grad = True
x

tensor([[0.0441, 0.3737, 0.6619],
        [0.4848, 0.2443, 0.4555],
        [0.1655, 0.1121, 0.4600]], requires_grad=True)

In [5]:
loss = F.mse_loss(x, target)
loss

tensor(0.1345, grad_fn=<MseLossBackward0>)

In [6]:
threshold = 1e-5
lr = 1
epoch = 0

while loss > threshold:
    epoch += 1
    
    # 편미분계산
    loss.backward()
    
    x = x-lr*x.grad
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print(f'{epoch} Loss: {loss:.4}')
    print(x)

1 Loss: 0.08135
tensor([[0.0565, 0.3351, 0.5815],
        [0.4659, 0.3011, 0.4876],
        [0.2843, 0.2650, 0.5578]], requires_grad=True)
2 Loss: 0.04921
tensor([[0.0662, 0.3051, 0.5189],
        [0.4513, 0.3453, 0.5126],
        [0.3767, 0.3839, 0.6338]], requires_grad=True)
3 Loss: 0.02977
tensor([[0.0737, 0.2817, 0.4703],
        [0.4399, 0.3797, 0.5320],
        [0.4485, 0.4763, 0.6930]], requires_grad=True)
4 Loss: 0.01801
tensor([[0.0795, 0.2636, 0.4324],
        [0.4310, 0.4064, 0.5471],
        [0.5044, 0.5483, 0.7390]], requires_grad=True)
5 Loss: 0.01089
tensor([[0.0841, 0.2494, 0.4030],
        [0.4241, 0.4272, 0.5589],
        [0.5479, 0.6042, 0.7748]], requires_grad=True)
6 Loss: 0.00659
tensor([[0.0876, 0.2385, 0.3801],
        [0.4188, 0.4434, 0.5680],
        [0.5817, 0.6477, 0.8026]], requires_grad=True)
7 Loss: 0.003987
tensor([[0.0904, 0.2299, 0.3623],
        [0.4146, 0.4560, 0.5751],
        [0.6080, 0.6816, 0.8242]], requires_grad=True)
8 Loss: 0.002412
tensor([[

## 실습6.6 오토그래드
자동 미분 기능

In [7]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]
                      ]).requires_grad_(True)

In [8]:
x1 = x + 2
x1

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)

In [9]:
y = x1.sum()
y

tensor(18., grad_fn=<SumBackward0>)

In [11]:
y.backward()
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])
